# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180318_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_description',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.TextField(default='', max_length=20),
        ),
    ]
