# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180318_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
