# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20180427_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(max_length=1000),
        ),
    ]
